config/routes.rb
DigitalPost::Application.routes.draw do

  resources :libraries

  resources :documents

  resources :moments

  resources :timelines

  resources :case_studies

  resources :links

  resources :photos

  resources :languages

  resources :sectors

  resources :regions

  resources :work_zones

  resources :search, :only => [:index]

  resources :stages

  resources :units

  resources :staff, :only => [:index, :create, :destroy]
  resources :staff, :only => [:show], :controller => 'users'

  resources :volunteers, :only => [:index, :create, :destroy]
  resources :volunteers, :only => [:show], :controller => 'users'

  resources :references

  resources :valid_emails, :except => [:show]

  resources :revisions, :only => [:destroy]

  resources :pages do
    resources :revisions, :except => [:destroy]
  end

  authenticated :user do
    root :to => 'home#index'
  end
  
  #match '/search', :to => 'home#search', :as => :search
  root :to => "home#index"
  
  #devise_for :users
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
   
  resources :users, :except => [:new, :create]

=begin
  namespace :initiative, :path => '/:abbreviation', :constraints => { :abbreviation => /[a-z]{3,7}/i } do
    resources :countries
    get '/' => 'home#index', :as => :home
  end

  namespace :country, :path => '/:country_code', :constraints => { :country_code => /[a-z]{2}/i } do
    resources :initiatives
    get '/' => 'home#index', :as => :home
  end
=end

end

app/models/revision.rb
class Revision < ActiveRecord::Base
  attr_accessible :author_id, :content, :html, :page_id

  validates :author_id, :page_id, :content, :presence => true
  validates :author_id, :page_id, :numericality => { :is_integer => true }

  belongs_to :page
  belongs_to :author, :class_name => 'User', :foreign_key => :author_id

  default_scope :order => 'id DESC'

  before_validation :do_before_validation
  before_save :do_before_save
  after_save :do_after_save

  def next
    Revision.where(:page_id => page_id).where("id > ?", id).limit(1).first
  end

  def prev
    Revision.where(:page_id => page_id).where("id < ?", id).limit(1).first
  end

  def prev?
    Revision.where(:page_id => page_id).where("id < ?", id).any?
  end

  private

    def do_before_validation
    end

    def do_before_save
      self.html = Markdown.render(Reference.process_string(content, page))
    end

    def do_after_save
      self.page.set_html(html)
    end

end

app/controllers/revisions_controller.rb
class RevisionsController < ApplicationController
  load_and_authorize_resource

  # GET /revisions
  # GET /revisions.json
  def index
    @page = Page.find(params[:page_id])
    @revisions = @page.revisions

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @revisions }
    end
  end

  # GET /revisions/1
  # GET /revisions/1.json
  def show
    @page = Page.find(params[:page_id])
    @revision = @page.revisions.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @revision }
    end
  end

  # DELETE /revisions/1
  # DELETE /revisions/1.json
  def destroy
    @revision = Revision.find(params[:id])
    @revision.destroy

    respond_to do |format|
      format.html { redirect_to @revision.page }
      format.json { head :no_content }
    end
  end
end

app/helpers/revisions_helper.rb
module RevisionsHelper
end

app/views/revisions/_fields.html.haml
= f.hidden_field :author_id, :value => current_user.id
= f.text_area :content, :rows => 30, :class => 'span12 required markdown'

app/views/revisions/index.html.haml
- content_for :backtrack do
  %li= link_to raw("Pages &rang;"), pages_path
  %li= link_to raw("#{@page.title} &rang;"), @page
  %li.active= link_to raw("Revisions &rang;"), page_revisions_path(@page)
- content_for :top_right_menu do
  %li= link_to 'Edit Page', edit_page_path(@page)
.row-fluid
  .span12
    .well.green
      %h1
        %small #{pluralize(@revisions.count, 'Revision')} for 
        #{@page.title}
.row-fluid
  .span12
    %table.table.table-bordered
      %thead
        %th Raw Text
        %th Raw HTML
        %th Interpreted HTML
      %tbody
        - @revisions.each do |revision|
          %thead
            %th{:colspan => 3}
              = timeago(revision.created_at)
              by
              = revision.author.name
              = link_to 'view', [@page,revision]
          %tr
            %td
              %pre= revision.content
            %td
              %pre= revision.html
            %td
              - if revision.prev
                = raw markdown(Differ.diff_by_line(revision.content, revision.prev.content).format_as(:html))
              - else
                = raw revision.html

app/views/revisions/show.html.haml
- content_for :backtrack do
  %li= link_to raw("Pages &rang;"), pages_path
  %li= link_to raw("#{@page.title} &rang;"), @page
  %li= link_to raw("Revisions &rang;"), page_revisions_path(@page)
  %li.active= link_to 'Revision X', @revision
- content_for :top_right_menu do
  %li= link_to 'Edit Page', edit_page_path(@page)
.row-fluid
  .span12
    .well.green
      %h1
        = @page.title
        %small
          Authored by
          = @revision.author.name
          = timeago(@revision.created_at)
.row-fluid
  .span4
    .well.blue.center
      %h3 Raw Text
  .span4
    .well.red.center
      %h3 Raw HTML
  .span4
    .well.orange.center
      %h3 Interpreted HTML
.row-fluid
  .span4
    %pre= @revision.content
  .span4
    %pre= @revision.html
  .span4
    - if @revision.prev?
      = raw markdown(Differ.diff_by_line(@revision.content, @revision.prev.content).format_as(:html))
    - else
      = raw markdown(@revision.html)