config/routes.rb
DigitalPost::Application.routes.draw do

  resources :libraries

  resources :documents

  resources :moments

  resources :timelines

  resources :case_studies

  resources :links

  resources :photos

  resources :languages

  resources :sectors

  resources :regions

  resources :work_zones

  resources :search, :only => [:index]

  resources :stages

  resources :units

  resources :staff, :only => [:index, :create, :destroy]
  resources :staff, :only => [:show], :controller => 'users'

  resources :volunteers, :only => [:index, :create, :destroy]
  resources :volunteers, :only => [:show], :controller => 'users'

  resources :references

  resources :valid_emails, :except => [:show]

  resources :revisions, :only => [:destroy]

  resources :pages do
    resources :revisions, :except => [:destroy]
  end

  authenticated :user do
    root :to => 'home#index'
  end
  
  #match '/search', :to => 'home#search', :as => :search
  root :to => "home#index"
  
  #devise_for :users
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
   
  resources :users, :except => [:new, :create]

=begin
  namespace :initiative, :path => '/:abbreviation', :constraints => { :abbreviation => /[a-z]{3,7}/i } do
    resources :countries
    get '/' => 'home#index', :as => :home
  end

  namespace :country, :path => '/:country_code', :constraints => { :country_code => /[a-z]{2}/i } do
    resources :initiatives
    get '/' => 'home#index', :as => :home
  end
=end

end

app/views/shared/_form_errors.html.haml
#error_explanation.alert.alert-error
  %h2= "#{pluralize(item.errors.count, "form error")}:"
  %ul
    - item.errors.full_messages.each do |msg|
      %li= msg

app/views/shared/_form_info.html.haml
.control-group
  .controls.required
    %p{:style => 'padding:10px;'}
      %strong Required
      fields are indicated by a light yellow background.
.control-group
  .controls.markdown
    %p{:style => 'padding:10px;'}
      %strong Markdown-enabled
      fields are indicated by a light blue background.

app/views/shared/_markdown_help.html.haml
%table.table.table-bordered
  %thead
    %th External Links
    %th effect
  %tbody
    %tr
      %td
        %pre [link text](http://example.url)
      %td= markdown '[link text](http://example.url)'
    %tr
      %td ![alt text](image_url)
      %td= markdown '![alt text](http://placehold.it/50x50)'
  %thead
    %th Text Styles
    %th effect
  %tbody
    %tr
      %td # H1 header
      %td= markdown '# H1 header'
    %tr
      %td ## H2 header, etc. (1-6)
      %td= markdown '## H2 header, etc. (1-6)'
    %tr
      %td
        %pre Paragraph on new line
      %td= markdown 'Paragraph on new line'
    %tr
      %td
        %pre *emphasis*
      %td= markdown '*emphasis*'
    %tr
      %td
        %pre **strong**
      %td= markdown('**strong**')
    %tr
      %td
        %pre `code`
      %td= markdown '`code`'
  %thead
    %th Lists
    %th effect
  %tbody
    %tr
      %td
        %pre * item 1
      %td= markdown '* item 1'
    %tr
      %td
        %pre 1. numbered item 1
      %td= markdown '1. numbered item 1'
  -#%tr
    %td
      %p
        [End link][0], and [end link][1]
        %br
        \...
        [0]:http://test.com
        %br
        [1]:http://test.com
    %td= markdown ''

app/views/shared/_vmenu_list.html.haml
%li.nav-header= t('word.things')
%li= link_to icon_for('case_study', CaseStudy.model_name.human(:count => :plural)), case_studies_path
%li= link_to icon_for('library', Library.model_name.human(:count => :plural)), libraries_path
%li= link_to icon_for('link', Link.model_name.human(:count => :plural)), links_path
%li= link_to icon_for('document', Document.model_name.human(:count => :plural)), documents_path
%li= link_to icon_for('page', Page.model_name.human(:count => :plural)), pages_path
%li= link_to icon_for('photo', Photo.model_name.human(:count => :plural)), photos_path
%li= link_to icon_for('timeline', Timeline.model_name.human(:count => :plural)), timelines_path
- if can? :read, User
  %li.nav-header= t 'word.people'
  %li= link_to icon_for('user', t('word.everyone').titleize), users_path
  %li= link_to icon_for('staff', Staff.model_name.human(:count => :plural)), staff_index_path if can? :read, Staff
  %li= link_to icon_for('volunteer', Volunteer.model_name.human(:count => :plural)), volunteers_path if can? :read, Volunteer
%li.nav-header= ENV['COUNTRY']
%li= link_to icon_for('unit', Unit.model_name.human(:count => :plural)), units_path if can? :read, Unit
%li= link_to icon_for('stage', Stage.model_name.human(:count => :plural)), stages_path if can? :read, Stage
%li= link_to icon_for('sector', Sector.model_name.human(:count => :plural)), sectors_path if can? :read, Sector
%li= link_to icon_for('work_zone', WorkZone.model_name.human(:count => :plural)), work_zones_path if can? :read, WorkZone
%li= link_to icon_for('region', Region.model_name.human(:count => :plural)), regions_path if can? :read, Region
%li= link_to icon_for('language', Language.model_name.human(:count => :plural)), languages_path if can? :read, Language

app/views/shared/_wiki_help.html.haml
%table.table.table-bordered
  %thead
    %th Internal Links
    %th effect
  %tbody
    %tr
      %td
        %pre= "[language[Language Name]]\n[region[Region Name]]\n[sector[Sector Name]]\n[unit[Unit Name]]\n[user[User Name]]\n[user[Jack Brown]]\n[work_zone[Work Zone Name]]"
      %td
        = link_to Page.first.title, Page.first
        %br
        = link_to 'Jack Brown', User.find_by_email('jack@brownjohnf.com')