config/routes.rb
DigitalPost::Application.routes.draw do

  resources :libraries

  resources :documents

  resources :moments

  resources :timelines

  resources :case_studies

  resources :links

  resources :photos

  resources :languages

  resources :sectors

  resources :regions

  resources :work_zones

  resources :search, :only => [:index]

  resources :stages

  resources :units

  resources :staff, :only => [:index, :create, :destroy]
  resources :staff, :only => [:show], :controller => 'users'

  resources :volunteers, :only => [:index, :create, :destroy]
  resources :volunteers, :only => [:show], :controller => 'users'

  resources :references

  resources :valid_emails, :except => [:show]

  resources :revisions, :only => [:destroy]

  resources :pages do
    resources :revisions, :except => [:destroy]
  end

  authenticated :user do
    root :to => 'home#index'
  end
  
  #match '/search', :to => 'home#search', :as => :search
  root :to => "home#index"
  
  #devise_for :users
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
   
  resources :users, :except => [:new, :create]

=begin
  namespace :initiative, :path => '/:abbreviation', :constraints => { :abbreviation => /[a-z]{3,7}/i } do
    resources :countries
    get '/' => 'home#index', :as => :home
  end

  namespace :country, :path => '/:country_code', :constraints => { :country_code => /[a-z]{2}/i } do
    resources :initiatives
    get '/' => 'home#index', :as => :home
  end
=end

end

app/models/document.rb
class Document < ActiveRecord::Base
  attr_accessible :author, :description, :file, :file_content_type, :file_file_size, :file_hash, :language_id, :photo, :remove_file, :remove_photo, :remove_source, :restricted, :source, :source_content_type, :source_file_size, :title, :user_id

  # elasticsearch indexing
  include Tire::Model::Search
  include Tire::Model::Callbacks
  index_name ELASTICSEARCH_INDEX
  mapping do
    indexes :handle, :as => 'title'
    indexes :author
    indexes :description
    indexes :file
    indexes :language, :as => proc { |d| d.language.name }
    indexes :restricted
    indexes :source
    indexes :title
    indexes :user, :as => proc { |d| d.user.name }
  end

  mount_uploader :file, DocumentUploader
  mount_uploader :photo, PhotoUploader
  mount_uploader :source, DocumentUploader

  validates :author, :length => { :maximum => 255 }
  validates :file, :presence => true
  validates :language_id, :user_id, :presence => true, :numericality => { :is_integer => true }
  validates :photo,
    :file_size => {
      :maximum => 10.megabytes.to_i
    }
  validates :title, :presence => true, :length => { :maximum => 255 }

  belongs_to :language
  belongs_to :user

  has_many :stacks, :as => :stackable, :dependent => :destroy
  has_many :stackers, :through => :stacks, :source => :user
  has_many :libraries, :through => :stacks

  default_scope :order => 'id DESC'

  def to_param
    "#{id}-#{title.parameterize}"
  end

  private

    before_validation do |this_doc|
      this_doc.title = file.file.original_filename if title.blank? && !file.blank?
    end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  load_and_authorize_resource

  # GET /documents
  # GET /documents.json
  def index
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @documents }
    end
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
    @document = Document.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @document }
    end
  end

  # GET /documents/new
  # GET /documents/new.json
  def new
    @document = Document.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @document }
    end
  end

  # GET /documents/1/edit
  def edit
    @document = Document.find(params[:id])
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = current_user.documents.build(params[:document])

    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: 'Document was successfully created.' }
        format.json { render json: @document, status: :created, location: @document }
      else
        format.html { render action: "new" }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /documents/1
  # PUT /documents/1.json
  def update
    @document = Document.find(params[:id])

    respond_to do |format|
      if @document.update_attributes(params[:document])
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document = Document.find(params[:id])
    @document.destroy

    respond_to do |format|
      format.html { redirect_to documents_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.haml
= form_for @document do |f|
  = render 'shared/form_errors', :item => @document if @document.errors.any?
  = render 'shared/form_info'
  .row-fluid
    .span6
      = f.label :file
      = f.file_field :file, :class => 'span12 required'
    .span6
      = f.label :source
      = f.file_field :source, :class => 'span12 required'
  .row-fluid
    .span6
      = f.label :title
      = f.text_field :title, :class => 'span12'
      = f.label :author
      = f.text_field :author, :class => 'span12'
      = f.label :description
      = f.text_area :description, :rows => 6, :class => 'span12'
      = f.label :language_id
      = f.collection_select :language_id, Language.all, :id, :name, {}, :class => 'span12 required'
      = f.label :restricted, :class => 'checkbox' do
        = f.check_box :restricted
        = t 'activerecord.attributes.document.restricted'
    .span6
      = f.label :photo
      = f.file_field :photo, :class => 'span12'
      - if @document.photo?
        %label.checkbox
          = f.check_box :remove_photo
          Remove
      %span.help-block the photo will be used to visually identify this document
      = image_tag(@document.photo.golden791.url)
  .form-actions
    = f.submit 'Save', :class => 'btn btn-primary'

app/views/documents/edit.html.haml
- content_for :backtrack do
  %li= link_to raw("#{icon_for('document', Document.model_name.human(:count => :plural))} &rang;"), documents_path
  %li= link_to raw("#{@document.title} &rang;"), @document
  %li.active= link_to raw(action_icon(:edit)), edit_document_path(@document) if can? :edit, @document

- content_for :top_right_menu do
  %li= link_to raw(action_icon(:upload, t('phrase.upload_resource', :resource => Document.model_name.human))), new_document_path if can? :create, Document

= render 'form'

app/views/documents/index.html.haml
- content_for :backtrack do
  %li.active= link_to raw("#{icon_for('document', Document.model_name.human(:count => :plural))}"), documents_path

- content_for :top_right_menu do
  %li= link_to raw(action_icon(:upload, t('phrase.upload_resource', :resource => Document.model_name.human))), new_document_path if can? :create, Document

.well.blue
  %h1= Document.model_name.human(:count => :plural)

%table.table.table-condensed
  %thead
    %th
    %th= t 'activerecord.attributes.document.title'
    %th= t 'activerecord.attributes.document.author'
    %th= t 'activerecord.attributes.document.description'
    %th= t 'activerecord.attributes.document.file_content_type'
    %th= t 'activerecord.attributes.document.file_file_size'
    %th= t 'activerecord.attributes.document.user_id'
  - @documents.each do |document|
    %tr
      %td= link_to document.language.code, document.language
      %td= link_to document.title, document
      %td= document.author
      %td= document.description
      %td= document.file_content_type
      %td= document.file_file_size
      %td= link_to document.user.name, document.user

app/views/documents/new.html.haml
- content_for :backtrack do
  %li= link_to raw("#{icon_for('document', Document.model_name.human(:count => :plural))}"), documents_path

- content_for :top_right_menu do
  %li.active= link_to raw(action_icon(:upload, t('phrase.upload_resource', :resource => Document.model_name.human))), new_document_path if can? :create, Document

= render 'form'

app/views/documents/show.html.haml
- content_for :backtrack do
  %li= link_to raw("#{icon_for('document', Document.model_name.human(:count => :plural))} &rang;"), documents_path
  %li.active= link_to raw("#{@document.title}"), @document
  %li= link_to raw(action_icon(:edit)), edit_document_path(@document) if can? :edit, @document

- content_for :top_right_menu do
  %li= link_to raw(action_icon(:upload, t('phrase.upload_resource', :resource => Document.model_name.human))), new_document_path if can? :create, Document

- content_for :bottom_right_menu do
  = destroy_button(@document) if can? :destroy, @document

- if @document.restricted?
  .alert.alert-error
    %b RESTRICTED CONTENT.
    You are viewing a restricted #{Document.model_name.human.downcase}. Only other staff and PCVs will be able to view it.
.row-fluid
  .span6
    Libraries:
  .span6
    .right
      = link_to 'add to library', '', :class => 'btn btn-success'
.page-header
  %h1
    = @document.title
    %small #{@document.file_content_type}, #{@document.file_file_size}
  %p
    = icon_for('tags')
    = link_to 'tags', ''
  %p
    = link_to 'download', ''
    = link_to 'download source', '' if @document.source?
.row-fluid
  .span6
    %h3= @document.author
    %blockquote
      %p= @document.description
      %small= @document.user.name
  .span6
    %p.right
      %span.label.label-info
        = @document.language.name
      %br
      = @document.file.url
      %br
      = @document.source.url
%p= 'This is a private file.' if @document.restricted?