config/routes.rb
DigitalPost::Application.routes.draw do

  resources :libraries

  resources :documents

  resources :moments

  resources :timelines

  resources :case_studies

  resources :links

  resources :photos

  resources :languages

  resources :sectors

  resources :regions

  resources :work_zones

  resources :search, :only => [:index]

  resources :stages

  resources :units

  resources :staff, :only => [:index, :create, :destroy]
  resources :staff, :only => [:show], :controller => 'users'

  resources :volunteers, :only => [:index, :create, :destroy]
  resources :volunteers, :only => [:show], :controller => 'users'

  resources :references

  resources :valid_emails, :except => [:show]

  resources :revisions, :only => [:destroy]

  resources :pages do
    resources :revisions, :except => [:destroy]
  end

  authenticated :user do
    root :to => 'home#index'
  end
  
  #match '/search', :to => 'home#search', :as => :search
  root :to => "home#index"
  
  #devise_for :users
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
   
  resources :users, :except => [:new, :create]

=begin
  namespace :initiative, :path => '/:abbreviation', :constraints => { :abbreviation => /[a-z]{3,7}/i } do
    resources :countries
    get '/' => 'home#index', :as => :home
  end

  namespace :country, :path => '/:country_code', :constraints => { :country_code => /[a-z]{2}/i } do
    resources :initiatives
    get '/' => 'home#index', :as => :home
  end
=end

end

app/models/unit.rb
class Unit < ActiveRecord::Base
  attr_accessible :description, :head_id, :name, :photo, :photo_content_type, :photo_file_size, :photo_hash, :remove_photo
  
  # elasticsearch indexing
  include Tire::Model::Search
  include Tire::Model::Callbacks
  index_name ELASTICSEARCH_INDEX
  mapping do
    indexes :handle, :as => 'name'
    indexes :description
    indexes :name
  end

  mount_uploader :photo, PhotoUploader

  validates :photo,
    :file_size => {
      :maximum => 10.megabytes.to_i
    }
  validates :photo_file_size,
    :numericality => { :is_integer => true },
    :allow_blank => true
  validates :name,
    :presence => true,
    :length => { :maximum => 255 },
    :uniqueness => { :case_sensitive => false }
  validates :head_id,
    :numericality => { :is_integer => true },
    :allow_blank => true
  validates :description,
    :length => { :maximum => 255 },
    :allow_blank => true

  belongs_to :head, :class_name => 'Staff', :foreign_key => :head_id
  has_many :staff, :dependent => :nullify
  has_many :users, :through => :staff

  default_scope :order => 'name ASC'

  def head?
    !head.nil?
  end

  def to_param
    "#{id}-#{name.parameterize}"
  end

end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  load_and_authorize_resource

  # GET /units
  # GET /units.json
  def index
    @units = Unit.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @units }
    end
  end

  # GET /units/1
  # GET /units/1.json
  def show
    @unit = Unit.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @unit }
    end
  end

  # GET /units/new
  # GET /units/new.json
  def new
    @unit = Unit.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @unit }
    end
  end

  # GET /units/1/edit
  def edit
    @unit = Unit.find(params[:id])
  end

  # POST /units
  # POST /units.json
  def create
    @unit = Unit.new(params[:unit])

    respond_to do |format|
      if @unit.save
        format.html { redirect_to @unit, notice: 'Unit was successfully created.' }
        format.json { render json: @unit, status: :created, location: @unit }
      else
        format.html { render action: "new" }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /units/1
  # PUT /units/1.json
  def update
    @unit = Unit.find(params[:id])

    respond_to do |format|
      if @unit.update_attributes(params[:unit])
        format.html { redirect_to @unit, notice: 'Unit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1
  # DELETE /units/1.json
  def destroy
    @unit = Unit.find(params[:id])
    @unit.destroy

    respond_to do |format|
      format.html { redirect_to units_url }
      format.json { head :no_content }
    end
  end
end

app/views/units/_form.html.haml
.row-fluid
  .span8
    = form_for @unit do |f|
      = render 'shared/form_errors', :item => @unit if @unit.errors.any?
      = render 'shared/form_info'
      .row-fluid
        .span6
          = f.label :name, 'Unit Name'
          = f.text_field :name, :class => 'required span12'
          = f.label :head_id, 'Head of Unit'
          = f.collection_select :head_id, Staff.all, :id, :name, {:include_blank => true}, :class => 'required span12'
          %span.help-block staff member responsible for the unit
          = f.label :description, 'Duties & Jurisdiction'
          = f.text_area :description, :rows => 7, :class => 'span12'
        .span6
          = f.label :photo
          = f.file_field :photo, :class => 'span12'
          - if @unit.photo?
            %label.checkbox
              = f.check_box :remove_photo
              Remove
          %span.help-block the photo will be used to visually identify this #{Unit.model_name.human.downcase}
          = image_tag(@unit.photo.golden791.url)
      .form-actions
        = f.submit 'Save', :class => 'btn btn-primary'
  .span4
    .well.orange
      %h1 Instructions
    %p Specify a name for the unit; set the staff member responsible for the unit; describe the duties and jurisdiction of the unit.

app/views/units/edit.html.haml
- content_for :backtrack do
  %li= link_to raw('Units &rang;'), units_path
  %li= link_to raw("#{@unit.name} &rang;"), @unit
  %li.active= link_to 'Edit', edit_unit_path(@unit)
- content_for :top_right_menu do
  %li= link_to raw('<span class="icon-plus"></span> New Unit'), new_unit_path if can? :create, Unit

= render 'form'

app/views/units/index.html.haml
- content_for :backtrack do
  %li.active= link_to 'Units', units_path
- content_for :top_right_menu do
  %li= link_to raw('<span class="icon-plus"></span> New Unit'), new_unit_path if can? :create, Unit
.row-fluid
  .span8
    %ul.thumbnails
      - for unit in @units do
        %li.span4
          = link_to unit, :class => 'thumbnail', :rel => 'popover', 'data-trigger' => 'hover', 'title' => unit.name, 'data-content' => unit.description, 'data-placement' => 'bottom' do
            = image_tag unit.photo.golden374.url
            %h3.center #{unit.name} Unit
  .span4
    .well.green
      %h1 Select a Unit
    %p Select the unit you're looking for from the options on the left. In each unit's section you will find:
    %ul.no-bullet
      %li Staff contact info
      %li Official resources/documents
    %p Hover over the unit for a description of its responsibilities.

app/views/units/new.html.haml
- content_for :backtrack do
  %li= link_to raw('Units &rang;'), units_path
  %li.active= link_to 'New Unit', new_unit_path

= render 'form'

app/views/units/show.html.haml
- content_for :backtrack do
  %li= link_to raw('Units &rang;'), units_path
  %li.active= link_to raw("#{@unit.name} &rang;"), @unit
  %li= link_to 'Edit', edit_unit_path(@unit) if can? :edit, @unit
- content_for :top_right_menu do
  - for unit in Unit.where("id != ?", @unit.id) do
    %li= link_to unit.name, unit
  %li= link_to raw('<span class="icon-plus"></span> New Unit'), new_unit_path if can? :create, Unit

.row-fluid
  .span4
    = image_tag @unit.photo.golden791.url
    %h1 What We Do
    %blockquote= @unit.description
  .span8
    .well.blue
      %h1
        = "#{@unit.head.user.fname} and the" if @unit.head?
        = @unit.name
        Team
    .row-fluid
      .span6
        %h1 Libraries
      .span6
        %h1 Staff
        %ul.nav.nav-tabs.nav-stacked
          - for staff in @unit.staff do
            %li
              = link_to staff.user do
                = "#{staff.name}"
                = "| #{staff.job_title}" unless staff.job_title.blank?